name: "AI Dependency & Migration Validator"
description: "Validate dependency versioning and database migrations using AI"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model"
    required: false
    default: "gpt-4"
  exclude:
    description: "Glob patterns to exclude files from analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/src/main.js"
branding:
  icon: "shield"
  color: "blue"